# SPDX-License-Identifier: AGPL-3.0-or-later

[workspace]
members = [
    "crates/crossscp-core",
    "crates/crossscp-cli",
    "crates/crossscp-config",
    "crates/crossscp-platform-macos",
    "crates/crossscp-platform-windows",
    "crates/crossscp-protocol-local",
    "crates/crossscp-protocol-scp",
    "crates/crossscp-protocol-sftp",
    "crates/crossscp-protocol-ftp",
    "crates/crossscp-protocol-http",
    "crates/crossscp-protocol-webdav",
    "crates/crossscp-protocol-s3",
    "crates/crossscp-security",
    "crates/crossscp-transfer",
]
resolver = "2"

[workspace.package]
version = "1.0.2"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/pat229988/Cross-SCP"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"
