# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "crossscp-security"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "crossscp_security"
path = "src/lib.rs"

[dependencies]
zeroize = { version = "1.8.2", features = ["derive"] }

[lints]
workspace = true
