# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "crossscp-protocol-local"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "crossscp_protocol_local"
path = "src/lib.rs"

[dependencies]
crossscp-core = { path = "../crossscp-core" }
crossscp-transfer = { path = "../crossscp-transfer" }

[lints]
workspace = true
