# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "crossscp-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "crossscp"
path = "src/main.rs"

[dependencies]
crossscp-config = { path = "../crossscp-config" }
crossscp-core = { path = "../crossscp-core" }
crossscp-protocol-local = { path = "../crossscp-protocol-local" }
crossscp-protocol-ftp = { path = "../crossscp-protocol-ftp" }
crossscp-protocol-scp = { path = "../crossscp-protocol-scp" }
crossscp-protocol-sftp = { path = "../crossscp-protocol-sftp" }
crossscp-security = { path = "../crossscp-security" }
crossscp-transfer = { path = "../crossscp-transfer" }

[features]
default = []
ssh2-backend = ["crossscp-protocol-sftp/ssh2-backend"]

[lints]
workspace = true
