# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "crossscp-platform-macos"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "crossscp_platform_macos"
path = "src/lib.rs"

[dependencies]
crossscp-security = { path = "../crossscp-security" }

[lints]
workspace = true
