# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "crossscp-protocol-sftp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "crossscp_protocol_sftp"
path = "src/lib.rs"

[dependencies]
crossscp-core = { path = "../crossscp-core" }
crossscp-security = { path = "../crossscp-security" }
ssh2 = { version = "0.9.5", optional = true }

[features]
default = []
ssh2-backend = ["dep:ssh2"]

[lints]
workspace = true
