# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "crossscp-protocol-s3"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crossscp-core = { path = "../crossscp-core" }
crossscp-protocol-http = { path = "../crossscp-protocol-http" }

[lints]
workspace = true
